baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Live Free or Dichotomize"
theme = "hugo-theme-casper"
googleAnalytics = ""
disqusShortname = ""
publishDir = "docs"


[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/LFOD/blog"
[[menu.main]]
    name = "Lucy"
    url = "https://twitter.com/lucystats"
[[menu.main]]
    name = "Nick"
    url = "https://twitter.com/nicholasstrayer"

[params]
    description = "A statistics blog from two great Phd students."
    logo = "images/logo.png"