baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Live Free or Dichotomize"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
publishDir = "docs"


[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/rstudio/blogdown"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/rstudio"

[params]
    description = "A statistics blog from two great Phd students."

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
